import { ModelDefinition } from '@nestjs/mongoose';
import {
  Activity,
  ActivityLog,
  ActivityLogSchema,
  ActivitySchema,
  Document,
  DocumentFolder,
  DocumentFolderSchema,
  DocumentSchema,
  Expense,
  ExpenseSchema,
  ExpenseSplit,
  ExpenseSplitSchema,
  Location,
  LocationSchema,
  Message,
  MessageAttachment,
  MessageAttachmentSchema,
  MessageSchema,
  Notification,
  NotificationSchema,
  Photo,
  PhotoSchema,
  Settlement,
  SettlementSchema,
  Trip,
  TripDay,
  TripDaySchema,
  TripInvite,
  TripInviteSchema,
  TripMember,
  TripMemberSchema,
  TripSchema,
  User,
  UserSchema,
} from './schemas';

// Central registration keeps DatabaseModule focused on connection wiring.
export const mongoModelDefinitions: ModelDefinition[] = [
  { name: User.name, schema: UserSchema },
  { name: Trip.name, schema: TripSchema },
  { name: TripMember.name, schema: TripMemberSchema },
  { name: TripInvite.name, schema: TripInviteSchema },
  { name: TripDay.name, schema: TripDaySchema },
  { name: Activity.name, schema: ActivitySchema },
  { name: Expense.name, schema: ExpenseSchema },
  { name: ExpenseSplit.name, schema: ExpenseSplitSchema },
  { name: Settlement.name, schema: SettlementSchema },
  { name: Location.name, schema: LocationSchema },
  { name: DocumentFolder.name, schema: DocumentFolderSchema },
  { name: Document.name, schema: DocumentSchema },
  { name: Photo.name, schema: PhotoSchema },
  { name: Message.name, schema: MessageSchema },
  { name: MessageAttachment.name, schema: MessageAttachmentSchema },
  { name: Notification.name, schema: NotificationSchema },
  { name: ActivityLog.name, schema: ActivityLogSchema },
];
